baseURL = 'https://datawaller.com/'
languageCode = 'en-gb'
title = 'James Waller'
theme = 'coder'
favicon_32 = 'images/favicon-32x32.png'
favicon_16 = 'images/favicon-16x16.png'
favicon_svg = 'images/favicon.svg'

[params]
  author = "James Waller"
  info = "Data Leader"
  description = "Writing about Analytics and Software Engineering"
  keywords = "blog,developer,analytics engineer,dbt"
  colorScheme = "auto"
  avatarurl = "/images/profile.jpeg"

    [[params.social]]
        name = "Github"
        icon = "fa fa-github fa-2x"
        weight = 1
        url = "https://github.com/wallyflops/"
    [[params.social]]
        name = "LinkedIn"
        icon = "fa fa-linkedin fa-2x"
        weight = 1
        url = "https://www.linkedin.com/in/jcwaller1/"
[menu]
  [[menu.main]]
    name = "Blog"
    weight = 1
    url = "/posts/"
